<?xml version="1.0"?>
<package format="3">
  <name>rubi_mapping_bringup</name>
  <version>0.1.0</version>
  <description>RUBI configuration for CuPy elevation and global persistence.</description>
  <maintainer email="127925120+Kimgyoomin@users.noreply.github.com">Kimgyoomin</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>elevation_mapping_cupy</exec_depend>
  <exec_depend>rubi_global_heightmap_wrapper</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
